const book = (author, title, category, year, description, reviews = {}) =>
    ({ author, title, category, year, description, reviews });

let books = {
    1: book("Marcus Aurelius", "Meditations", "Stoicism", "170–180 AD",
        "The private notes of a philosopher emperor: daily exercises to stay calm, fair and in control of oneself.",
        {
            sofia: "I keep it on my nightstand. A few pages a day are enough to put things back in perspective.",
            luca: "It is surprising how current it is: it talks about anxiety, anger and ego as if it were written yesterday.",
        }),
    2: book("Seneca", "Letters to Lucilius", "Stoicism", "62–65 AD",
        "124 letters to a friend on time, death, friendship and the pursuit of wisdom, written in the last years of his life.",
        { giorgia: "Every letter is a small essay. The first one, on the value of time, is worth the whole book." }),
    3: book("Epictetus", "Enchiridion", "Stoicism", "2nd century AD",
        "The core of Stoicism in a few pages: telling apart what is up to us from what is not."),
    4: book("Seneca", "On the Shortness of Life", "Stoicism", "49 AD",
        "Life is not short: we are the ones who waste it. A brief dialogue on how to truly use our time.",
        { luca: "Short and sharp. One to reread every time I complain about not having time." }),
    5: book("Plato", "Apology of Socrates", "Ancient philosophy", "4th century BC",
        "Socrates' defense before the judges of Athens: a life devoted to dialogue and the search for truth."),
    6: book("Epicurus", "Letter on Happiness", "Ancient philosophy", "3rd century BC",
        "The Letter to Menoeceus: freeing oneself from the fear of the gods and of death, and cultivating simple pleasures and friendship."),
    7: book("Immanuel Kant", "Critique of Pure Reason", "Modern philosophy", "1781",
        "What can we know? Kant explores the limits and conditions of human knowledge and revolutionizes philosophy.",
        { sofia: "Demanding, but with a good introduction at hand a whole world opens up. One to read slowly." }),
    8: book("Immanuel Kant", "Groundwork of the Metaphysics of Morals", "Modern philosophy", "1785",
        "The categorical imperative: act only according to maxims you could will to become a universal law."),
    9: book("Arthur Schopenhauer", "The World as Will and Representation", "Modern philosophy", "1819",
        "Behind the world of appearances a blind will is at work: art, compassion and asceticism as paths to liberation."),
    10: book("Friedrich Nietzsche", "Thus Spoke Zarathustra", "Modern philosophy", "1883–1885",
        "A book for all and none: in poetic form, the announcement of the overman, the death of God and the eternal return.",
        { giorgia: "More poetry than treatise. Not everything is clear, but some pages stay with you for days." }),
    11: book("Friedrich Nietzsche", "Beyond Good and Evil", "Modern philosophy", "1886",
        "A radical critique of traditional morality and of the philosophers' prejudices, in brilliant and provocative aphorisms."),
    12: book("Søren Kierkegaard", "Either/Or", "Existentialism", "1843",
        "Aesthetic life or ethical life? Kierkegaard puts the reader face to face with the responsibility of choosing."),
    13: book("Albert Camus", "The Myth of Sisyphus", "Existentialism", "1942",
        "Faced with the absurdity of life, the answer is not surrender but revolt: one must imagine Sisyphus happy."),
    14: book("Viktor E. Frankl", "Man's Search for Meaning", "Psychology", "1946",
        "The experience of the concentration camps and the birth of logotherapy: those who have a why can bear almost any how.",
        {
            luca: "One of the most important books I have ever read. Harsh but full of hope.",
            sofia: "The link with Stoicism is clear: the freedom to choose one's own attitude.",
        }),
    15: book("Carl Gustav Jung", "Man and His Symbols", "Psychology", "1964",
        "The most accessible introduction to Jung's thought: the collective unconscious, archetypes and the language of dreams."),
    16: book("Sigmund Freud", "The Interpretation of Dreams", "Psychology", "1899",
        "The work that founded psychoanalysis: dreams as the royal road to knowledge of the unconscious."),
    17: book("Daniel Kahneman", "Thinking, Fast and Slow", "Psychology", "2011",
        "The Nobel laureate explains the two systems of thought, intuitive and reflective, and the systematic errors in our judgment.",
        { giorgia: "It changes the way you look at your decisions. Long, but every chapter has a strong idea." }),
    18: book("Erich Fromm", "The Art of Loving", "Psychology", "1956",
        "Love is not a feeling but an art that requires discipline, patience and self-knowledge."),
};

module.exports = books;
